apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-things
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
        - env:
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: iot-things
                  resource: limits.memory
            - name: RABBITMQ_HOST
              value: rabbitmq
          image: ghcr.io/diwise/iot-things:changeme
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: default-port
          name: iot-things
          ports:
            - containerPort: 8080
              name: default-port
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 100Mi
          startupProbe:
            httpGet:
              path: /health
              port: default-port
          volumeMounts:
            - name: conf-volume
              mountPath: /opt/diwise/config
              readOnly: true
      serviceAccountName: iot-things
      volumes:
        - name: conf-volume
          configMap:
            name: iot-things-cfg-cm
